version: "3.9"
services:
  backend:
    build: ./backend
    command: python -m app
    environment:
      - PORT=8000
      - CORS_ORIGINS=*
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=gemini-1.5-flash
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    command: npm run dev -- --host
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
